create sequence hibernate_sequence start 1 increment 1;;

    create table tb_business (
       id int8 generated by default as identity,
        address varchar(255),
        name varchar(255),
        points float8 not null,
        tribute float8 not null,
        website varchar(255),
        user_id int8,
        primary key (id)
    );;

    create table tb_ong (
       id int8 generated by default as identity,
        address varchar(255),
        cnpj varchar(255),
        name varchar(255),
        user_id int8,
        primary key (id)
    );;

    create table tb_order_item (
       id int8 generated by default as identity,
        moment timestamp,
        ong_id int8,
        product_id int8,
        primary key (id)
    );;

    create table tb_permission (
       id int8 generated by default as identity,
        description varchar(255),
        primary key (id)
    );;

    create table tb_product (
       id int8 generated by default as identity,
        description varchar(255),
        due_date date,
        image_uri varchar(2000),
        name varchar(255),
        status varchar(255),
        business_id int8,
        index_column int4,
        primary key (id)
    );;

    create table tb_userman (
       id int8 not null,
        password varchar(255),
        username varchar(255),
        primary key (id)
    );;

    create table user_permission (
       id_user int8 not null,
        id_permission int8 not null
    );;

    alter table if exists tb_userman 
       add constraint UK_klxfntb6c2gomskcwrgq3bav1 unique (username);;

    alter table if exists tb_business 
       add constraint FKpu6yu2ggmw99wsq9bahu01qrx 
       foreign key (user_id) 
       references tb_userman;;

    alter table if exists tb_ong 
       add constraint FKk7n6m6vh7kw5r5u0c5pq5u14u 
       foreign key (user_id) 
       references tb_userman;;

    alter table if exists tb_order_item 
       add constraint FKj72bm0wi2sugbmeh4y3eueb40 
       foreign key (ong_id) 
       references tb_ong;;

    alter table if exists tb_order_item 
       add constraint FK4h5xid5qehset7qwe5l9c997x 
       foreign key (product_id) 
       references tb_product;;

    alter table if exists tb_product 
       add constraint FKgd3mvw2fp6twt3svx8smdnup 
       foreign key (business_id) 
       references tb_business;;

    alter table if exists user_permission 
       add constraint FK97s1m4j6o9m778dt672ipraq6 
       foreign key (id_permission) 
       references tb_permission;;

    alter table if exists user_permission 
       add constraint FKeb2moc9q5y0kb77r5jn4djcqe 
       foreign key (id_user) 
       references tb_userman;;
